// Rebuild the Rust wasm solver core and regenerate the embedded data module.
// Requires cargo + the wasm32-unknown-unknown target:
//   rustup target add wasm32-unknown-unknown
//   npm run build:wasm
// The generated src/wasm/solverWasmData.ts is COMMITTED so consumers never
// need a Rust toolchain — the JS solver also remains a full fallback.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))

execSync('cargo build --release --target wasm32-unknown-unknown', {
  cwd: join(root, 'rust'),
  stdio: 'inherit'
})

const wasm = readFileSync(join(root, 'rust/target/wasm32-unknown-unknown/release/bulba_pathfinder_core.wasm'))
const b64 = wasm.toString('base64')
const lines = []
for (let i = 0; i < b64.length; i += 120) lines.push(`  '${b64.slice(i, i + 120)}'`)

writeFileSync(join(root, 'src/wasm/solverWasmData.ts'), `// GENERATED by build-wasm.mjs — do not edit. Source: rust/src/lib.rs.
// ${wasm.length} bytes of wasm32-unknown-unknown release build.
export const wasmBase64: string | null = [
${lines.join(',\n')}
].join('')
`)

console.log(`[build-wasm] embedded ${wasm.length} bytes into src/wasm/solverWasmData.ts`)
