// Pumpkin server backend — a Minecraft server in Rust, used here because it
// boots in milliseconds instead of the ~16 s Paper takes, which is the
// dominant cost when iterating on a single route.
//
// Paper is still required once, for `arena:server --upgrade`: converting a
// 2018-era world to the current chunk format is Minecraft's DataFixerUpper,
// a vanilla-Java component Pumpkin does not carry. Once the world is
// upgraded, Pumpkin loads it directly.
import { createWriteStream } from 'node:fs'
import { access, chmod, mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import { join } from 'node:path'
import { PORT, RUN_DIR, VIEW_DISTANCE, WORLD_NAME } from './config.js'

const UA = 'bulba-pathfinder-arena/1.0 (+https://github.com/Vinciepincie/bulba-pathfinder)'
const RELEASES = 'https://api.github.com/repos/Pumpkin-MC/Pumpkin/releases/tags/nightly'

/** Release asset for this platform, e.g. `pumpkin-X64-Windows.exe`. */
function assetName (): string {
  const arch = process.arch === 'arm64' ? 'ARM64' : 'X64'
  const os = process.platform === 'win32' ? 'Windows' : process.platform === 'darwin' ? 'macOS' : 'Linux'
  return `pumpkin-${arch}-${os}${process.platform === 'win32' ? '.exe' : ''}`
}

export function pumpkinBinaryPath (): string {
  return join(RUN_DIR, assetName())
}

export async function downloadPumpkin (): Promise<string> {
  const out = pumpkinBinaryPath()
  try { await access(out); console.log(`pumpkin: ${out} (cached)`); return out } catch { /* fetch it */ }

  const res = await fetch(RELEASES, { headers: { 'User-Agent': UA, Accept: 'application/vnd.github+json' } })
  if (!res.ok) throw new Error(`pumpkin release lookup failed: ${res.status} ${res.statusText}`)
  const release = await res.json() as { tag_name: string, assets: Array<{ name: string, browser_download_url: string }> }
  const want = assetName()
  const asset = release.assets.find(a => a.name === want)
  if (asset === undefined) {
    throw new Error(`no pumpkin build named ${want} in release ${release.tag_name} (have: ${release.assets.map(a => a.name).join(', ')})`)
  }

  console.log(`downloading pumpkin ${release.tag_name} (${want}) ...`)
  await mkdir(RUN_DIR, { recursive: true })
  const bin = await fetch(asset.browser_download_url, { headers: { 'User-Agent': UA } })
  if (!bin.ok || bin.body === null) throw new Error(`pumpkin download failed: ${bin.status}`)
  await pipeline(Readable.fromWeb(bin.body as never), createWriteStream(`${out}.part`))
  await rename(`${out}.part`, out)
  if (process.platform !== 'win32') await chmod(out, 0o755)
  console.log(`pumpkin: ${out}`)
  return out
}

/**
 * Pumpkin is configured by TOML, not server.properties. `default_op_level = 4`
 * ops every player on join, which is what the arena wants: the referee runs
 * commands and nobody else is on a local benchmark server.
 */
export async function writePumpkinConfig (): Promise<void> {
  await mkdir(RUN_DIR, { recursive: true })
  await writeFile(join(RUN_DIR, 'configuration.toml'), [
    '# generated by bench/arena — edits are overwritten',
    `default_level_name = "${WORLD_NAME}"`,
    'default_gamemode = "Spectator"',
    'allow_chat_reports = false',
    '',
    '[networking.java]',
    'enabled = true',
    `address = "0.0.0.0:${PORT}"`,
    'online_mode = false',
    'max_players = 20',
    `view_distance = ${VIEW_DISTANCE}`,
    `simulation_distance = ${Math.min(VIEW_DISTANCE, 12)}`,
    'motd = "bulba-pathfinder arena (pumpkin)"',
    '',
    '[commands]',
    'use_console = true',
    'default_op_level = 4',
    ''
  ].join('\n'))

  // Some builds read pumpkin.toml instead of configuration.toml; write both
  // rather than guess at the version we happened to download.
  await writeFile(join(RUN_DIR, 'pumpkin.toml'), await readFile(join(RUN_DIR, 'configuration.toml')))
  await rm(join(RUN_DIR, 'features.toml'), { force: true })
}
