// Paper server lifecycle for the arena: fetch the jar, write a reproducible
// config, start/stop the process.
//
// No plugin is required. Everything the benchmark needs from the server —
// teleporting bots and spectators, disabling collision between the two
// racers, freezing weather/time/mobs — is a vanilla command run by an
// opped referee bot.
import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process'
import { createHash } from 'node:crypto'
import { createWriteStream } from 'node:fs'
import { access, mkdir, writeFile, readFile } from 'node:fs/promises'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import { join } from 'node:path'
import {
  BOT_NAMES, JAR_PATH, MC_VERSION, PORT, RUN_DIR, SERVER_HEAP, VIEW_DISTANCE, WORLD_NAME
} from './config.js'

const UA = 'bulba-pathfinder-arena/1.0 (+https://github.com/bulbastore)'

async function exists (path: string): Promise<boolean> {
  try { await access(path); return true } catch { return false }
}

/** Mojang's offline-mode UUID: md5 of "OfflinePlayer:<name>", as UUID v3. */
export function offlineUuid (name: string): string {
  const b = createHash('md5').update(`OfflinePlayer:${name}`, 'utf8').digest()
  b[6] = (b[6] & 0x0f) | 0x30
  b[8] = (b[8] & 0x3f) | 0x80
  const h = b.toString('hex')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`
}

export async function downloadPaper (): Promise<void> {
  if (await exists(JAR_PATH)) { console.log(`paper jar: ${JAR_PATH} (cached)`); return }

  const res = await fetch(`https://fill.papermc.io/v3/projects/paper/versions/${MC_VERSION}/builds`, {
    headers: { 'User-Agent': UA }
  })
  if (!res.ok) throw new Error(`paper build list failed: ${res.status} ${res.statusText}`)
  const builds = await res.json() as Array<{
    id: number
    channel: string
    downloads: Record<string, { url: string, checksums: { sha256: string } }>
  }>
  const stable = builds.filter(b => b.channel === 'STABLE')
  const build = (stable.length > 0 ? stable : builds).sort((a, b) => b.id - a.id)[0]
  const dl = build?.downloads['server:default']
  if (dl === undefined) throw new Error(`no server download for paper ${MC_VERSION}`)

  console.log(`downloading paper ${MC_VERSION} build ${build.id} ...`)
  await mkdir(RUN_DIR, { recursive: true })
  const jar = await fetch(dl.url, { headers: { 'User-Agent': UA } })
  if (!jar.ok || jar.body === null) throw new Error(`jar download failed: ${jar.status}`)
  await pipeline(Readable.fromWeb(jar.body as never), createWriteStream(`${JAR_PATH}.part`))

  const sha = createHash('sha256').update(await readFile(`${JAR_PATH}.part`)).digest('hex')
  if (sha !== dl.checksums.sha256) throw new Error(`jar checksum mismatch: ${sha} != ${dl.checksums.sha256}`)
  await writeFile(JAR_PATH, await readFile(`${JAR_PATH}.part`))
  console.log(`paper jar: ${JAR_PATH} (verified)`)
}

/**
 * Server config. Chosen for a benchmark, not for play:
 * offline-mode so bots can join unauthenticated, spectator on join so nobody
 * takes fall damage before the referee places them, and a generous view
 * distance so a whole route is loaded before either racer starts.
 */
export async function writeServerConfig (): Promise<void> {
  await mkdir(RUN_DIR, { recursive: true })
  await writeFile(join(RUN_DIR, 'eula.txt'), 'eula=true\n')

  await writeFile(join(RUN_DIR, 'server.properties'), [
    '# generated by bench/arena/setupServer.ts — edits are overwritten',
    `server-port=${PORT}`,
    'online-mode=false',
    'enforce-secure-profile=false',
    `level-name=${WORLD_NAME}`,
    'level-type=minecraft:normal',
    'gamemode=spectator',
    'force-gamemode=true',
    'difficulty=peaceful',
    'spawn-monsters=false',
    'spawn-protection=0',
    'allow-flight=true',
    'allow-nether=false',
    `view-distance=${VIEW_DISTANCE}`,
    `simulation-distance=${Math.min(VIEW_DISTANCE, 12)}`,
    'max-players=20',
    'sync-chunk-writes=false',
    'max-tick-time=-1',
    'pause-when-empty-seconds=-1',
    'motd=bulba-pathfinder arena',
    'white-list=false',
    ''
  ].join('\n'))

  await writeFile(join(RUN_DIR, 'ops.json'), JSON.stringify(
    BOT_NAMES.map(name => ({ uuid: offlineUuid(name), name, level: 4, bypassesPlayerLimit: true })),
    null, 2
  ))

  // Long-range parkour looks like "moving too quickly" to the vanilla check;
  // raising the thresholds stops the server rubber-banding a legitimate jump
  // and turning a pathfinder difference into a network artefact.
  await writeFile(join(RUN_DIR, 'spigot.yml'), [
    'settings:',
    '  moved-too-quickly-multiplier: 100.0',
    '  moved-wrongly-threshold: 10.0',
    '  timeout-time: 3600',
    ''
  ].join('\n'))

  await writeFile(join(RUN_DIR, 'bukkit.yml'), [
    'settings:',
    '  allow-end: false',
    'ticks-per:',
    '  animal-spawns: -1',
    '  monster-spawns: -1',
    ''
  ].join('\n'))

  // Chunk upgrades from a 2018-era world blow past the default watchdog.
  await mkdir(join(RUN_DIR, 'config'), { recursive: true })
  await writeFile(join(RUN_DIR, 'config', 'paper-global.yml'), [
    'watchdog:',
    '  early-warning-delay: 999999',
    '  early-warning-every: 999999',
    'chunk-system:',
    '  io-threads: -1',
    ''
  ].join('\n'))

  // Paper meters chunks to a player at 75/s by default. At view-distance 16
  // that is ~15 s of streaming after every teleport, and both engines drop
  // their path on each chunk that lands — the first run this way logged 531
  // path resets and zero completed solves. On localhost there is no reason to
  // meter at all.
  await writeFile(join(RUN_DIR, 'config', 'paper-world-defaults.yml'), [
    'chunk-loading-basic:',
    '  player-max-chunk-generate-rate: -1.0',
    '  player-max-chunk-load-rate: -1.0',
    '  player-max-chunk-send-rate: -1.0',
    'chunk-loading-advanced:',
    '  auto-config-send-distance: true',
    '  player-max-concurrent-chunk-generates: 0',
    '  player-max-concurrent-chunk-loads: 0.0',
    ''
  ].join('\n'))
}

export interface ServerHandle {
  proc: ChildProcessWithoutNullStreams
  send: (command: string) => void
  stop: () => Promise<void>
  /** Resolves when the process exits. */
  exited: Promise<number | null>
}

/** Start Paper and resolve once it reports "Done (…)". */
export async function startServer (extraArgs: string[] = [], quiet = true): Promise<ServerHandle> {
  const proc = spawn('java', [
    `-Xms${SERVER_HEAP}`, `-Xmx${SERVER_HEAP}`,
    '-XX:+UseG1GC', '-XX:MaxGCPauseMillis=50',
    '-Dcom.mojang.eula.agree=true',
    '-jar', JAR_PATH, '--nogui', ...extraArgs
  ], { cwd: RUN_DIR, stdio: ['pipe', 'pipe', 'pipe'] })

  const exited = new Promise<number | null>(resolve => proc.on('exit', code => resolve(code)))
  const send = (command: string): void => { proc.stdin.write(`${command}\n`) }

  await new Promise<void>((resolve, reject) => {
    let settled = false
    let locked = false
    const tail: string[] = []
    const onLine = (line: string): void => {
      if (!quiet) process.stdout.write(`[server] ${line}\n`)
      else if (/Preparing|Done \(|Force|upgrad|ERROR|Exception/i.test(line)) process.stdout.write(`[server] ${line}\n`)
      tail.push(line)
      if (tail.length > 8) tail.shift()
      // A previous run that did not shut down still owns the world's
      // session.lock. Paper reports this as a plain exit(0), which otherwise
      // surfaces as a baffling "exited before finishing startup".
      if (/DirectoryLock|Failed to start the minecraft server/i.test(line)) locked = true
      if (!settled && /\]: Done \(/.test(line)) { settled = true; resolve() }
    }
    lines(proc.stdout, onLine)
    lines(proc.stderr, onLine)
    proc.on('exit', code => {
      if (settled) return
      settled = true
      reject(new Error(locked
        ? `the arena world is locked by another server process — stop it and retry (world: ${WORLD_NAME})`
        : `server exited (${code}) before finishing startup:\n  ${tail.join('\n  ')}`))
    })
  })

  return {
    proc,
    send,
    exited,
    stop: async () => {
      if (proc.exitCode === null) { send('stop'); await exited }
    }
  }
}

/** One-shot: boot with --forceUpgrade so every chunk is converted up front
 *  and no run pays DataFixer cost mid-benchmark. */
export async function upgradeWorld (): Promise<void> {
  console.log('upgrading world chunks to the server version (one-time, slow) ...')
  const server = await startServer(['--forceUpgrade'], false)
  await server.stop()
  console.log('world upgrade complete')
}

function lines (stream: NodeJS.ReadableStream, onLine: (line: string) => void): void {
  let buf = ''
  stream.on('data', (chunk: Buffer) => {
    buf += chunk.toString('utf8')
    let i: number
    while ((i = buf.indexOf('\n')) >= 0) {
      onLine(buf.slice(0, i).replace(/\r$/, ''))
      buf = buf.slice(i + 1)
    }
  })
}
