// Parkour reach envelope, DERIVED from prismarine-physics — the exact engine
// (and held controls: forward+sprint+jump) the executor uses to gate every
// jump at run time. Generated by test/helpers/jumpEnvelope.ts;
// test/envelope.test.ts re-derives and asserts equality, so these values can
// never silently drift from the real physics.
//
// J[bucket] = usable flight distance (pure center travel minus a 0.1 safety
// margin) for a landing at dy = +1 (bucket 0), 0 (bucket 1), -1 … -8
// (buckets 2…9). Take-off and landing geometry is credited PER-AXIS by
// flightNeeded(): the 0.6-wide hitbox takes off from the block's corner and
// catches the landing block's near corner, so a diagonal (3,3) hop needs
// only ~2.26 blocks of flight, not the 4.24 center-to-center distance —
// exactly how players cross 1x1 pillar courses from a standstill.

export const ENVELOPE_BUCKETS = 10

/**
 * The safety margin already subtracted from every row below (the helper's
 * SAFETY_MARGIN): a plan never asks for a jump closer than this to the
 * physics limit, because a jump the executor's rollout then refuses is a
 * 3.5 s stall and a replan. `Movements.parkourSafetyMargin` re-tunes it per
 * profile — 0 plans the frame-tight jumps a practised player makes (the
 * arena's `--risky`), more is more conservative.
 */
export const ENVELOPE_SAFETY_MARGIN = 0.1

/** Standing start (a 1x1 pillar: no room to build sprint momentum). Pure
 * jam from the cell center; the executor creeps to the takeoff corner
 * (TAKEOFF_STAND per axis) before jumping — that credit is applied by
 * flightNeeded, not baked into these rows. */
export const J_STANDING: readonly number[] = [
  1.7856957298356373, 2.5234315139003862, 3.030990921511102, 3.2886681704338425, 3.8106837967864577, 4.074628686934417, 4.340298536969059, 4.607538100500584, 4.876206103314271, 5.146173985874726
]

/** Running start (≥1 walkable same-level cell behind the takeoff). Measured
 * with the jump firing at the cell center; the executor's rollout delays the
 * jump toward the lip, credited as TAKEOFF_RUN along the flight line. */
export const J_RUNNING: readonly number[] = [
  2.5757621249691116, 3.4272852710242216, 3.9946585989703007, 4.278268783720117, 4.845358445833772, 5.128845644365875, 5.412298995030089, 5.695721544134524, 5.97911606381956, 6.2624850767329425
]

/**
 * RUN-LENGTH envelope — the model a real player's jump follows. Nobody jumps
 * from rest at the lip: they sprint across whatever support they have and
 * jump at its edge, and even 0.4 blocks of run adds half a block of flight.
 * RUN_LENGTHS are the blocks of sprint before the jump the rows below were
 * measured at (0 = the jam from rest, i.e. J_STANDING); a fence post's
 * ±0.405 support zone gives ~0.8, a head's ~1.06, a full block ~1.38 (rear
 * overhang 0.78 to the 0.6 creep point), and each walkable cell behind —
 * level or one step lower — adds 1. Reach saturates around 2. Rows are
 * usable flight from the JUMP POINT per landing dy (buckets as J_STANDING),
 * so the per-axis lip credit applies exactly as for the jam. Derived by
 * measureRunTakeoff(); envelope.test.ts re-derives and asserts equality.
 * Recorded on the arena's parkouradv1: a human's pot-to-pot (5,-2) at
 * 0.277 blocks/tick average over 18 ticks — full sprint off a 0.25 post.
 */
export const RUN_LENGTHS: readonly number[] = [0,0.4,0.8,1.2,1.6,2,3]
export const J_RUN: ReadonlyArray<readonly number[]> = [
  [1.7856957298356373, 2.5234315139003862, 3.030990921511102, 3.2886681704338425, 3.8106837967864577, 4.074628686934417, 4.340298536969059, 4.607538100500584, 4.876206103314271, 5.146173985874726],
  [2.2448425003383314, 3.072799442818297, 3.627784865828414, 3.9060241479198683, 4.463778644123025, 4.743218486167964, 5.022988742428859, 5.3030596756262725, 5.5834042248359195, 5.863997764616698],
  [2.3453860036538257, 3.1930994857046064, 3.7584702104153744, 4.041212146087096, 4.606792704478114, 4.889625615684188, 5.172483564881715, 5.455364298651466, 5.7382657663819385, 6.021186102016669],
  [2.364773860726531, 3.2162970067816405, 3.78367033472772, 4.067280519477537, 4.634370181591191, 4.917857380123294, 5.201310730787508, 5.484733279891943, 5.768127799576979, 6.051496812490361],
  [2.3811394610873147, 3.235878405483103, 3.8049421628617615, 4.089285250550383, 4.657648771261976, 4.941688264194578, 5.225644202763246, 5.5095241068607335, 5.793334819589448, 6.077082568172577],
  [2.384295248485215, 3.239654296980699, 3.8090440207634457, 4.093528434514489, 4.662137594055178, 4.946283586209965, 5.230336439070822, 5.514304535174201, 5.7981955026282765, 6.082016283011485],
  [2.387753235616336, 3.2437917696811356, 3.813538674569071, 4.098177947834882, 4.667056268698188, 4.951318958492379, 5.235478006205092, 5.519542739623661, 5.803521647034559, 6.087422452778476]
]
/** Same runs under a solid lid 2 above the feet (head-hitter class). */
export const J_LOW_RUN: ReadonlyArray<readonly number[]> = [
  [-0.1, 0.9626976143129206, 1.8600178263100626, 2.292732225692906, 2.748396619821839, 2.9835742558313516, 3.466483304979486, 3.7134731393248104, 3.9637138885790555, 4.216912970400419],
  [-0.1, 0.8815489801948252, 1.9549023386659186, 2.4430631741072477, 2.944642761936213, 3.1997273989420587, 3.7172368065219197, 3.9792279795150525, 4.243119946938804, 4.508741637294417],
  [-0.1, 0.6517214113611253, 1.7805282904847677, 2.3453860036538257, 2.627905517934086, 3.1930994857046064, 3.4757647866002963, 3.7584702104153744, 4.041212146087096, 4.323987307548362],
  [-0.1, 0.943864544997134, 2.051629463425525, 2.550629157326545, 3.0611844038459797, 3.3201605293133847, 3.844433732988282, 4.1093574188328805, 4.375917972951465, 4.643968077199375],
  [-0.1, 0.6657803555144551, 1.8103637311992655, 2.3811394610873147, 2.6662247919356354, 3.235878405483103, 3.520477231335804, 3.8049421628617615, 4.089285250550383, 4.373517460347029],
  [-0.1, 0.6670212715536775, 1.812997163448238, 2.384295248485215, 2.669607051741299, 3.239654296980699, 3.5244237858721896, 3.8090440207634457, 4.093528434514489, 4.377889251027939],
  [-0.1, 0.6683810183152262, 1.8158827744477888, 2.387753235616336, 2.6733131983878926, 3.2437917696811356, 3.528748264386861, 3.813538674569071, 4.098177947834882, 4.382679686506771]
]
/** Row of the longest measured run not exceeding `runLength` (conservative). */
export function runRow (runLength: number): number {
  let row = 0
  for (let i = 1; i < RUN_LENGTHS.length; i++) if (RUN_LENGTHS[i] <= runLength) row = i
  return row
}

/**
 * Momentum chain: re-jump on the FIRST grounded tick after a sprint-jump
 * landing (jump released in the air, pressed on landing — the executor's
 * press-on-landing cadence). The landing speed carries into the takeoff,
 * so the second jump out-flies even a running start — this is how players
 * cross 1x1 courses where no post offers a run-up. Measured from the
 * weakest realistic incoming speed (a STANDING first jump over a 1-block
 * gap), usable flight per landing dy from the LANDING POINT; only valid
 * when the second jump continues the first one's direction (the solver
 * gates on the angle). Generated by measureChainTakeoff(); envelope.test.ts
 * re-derives and asserts equality.
 */
export const J_CHAIN: readonly number[] = [
  2.688724183712625, 3.6039027342842247, 4.2047374170597385, 4.502855113817017, 5.095160282550845, 5.389579921413924, 5.6829817927793265, 5.975457495721843, 6.267090385399532, 6.55795631500623
]
/**
 * A chained second jump keeps most of its momentum through a turn — the
 * re-jump re-accelerates in the new direction with sprint, so the reach
 * barely falls with the turn angle (measured, first-hop landing speed:
 * 0° 3.90 flat, 30° 3.81, 45° 3.70, 60° 3.56). The cutoff is where the
 * turned reach drops below J_CHAIN's promise (flat 3.60): 45°, cos 0.70.
 * Beyond that the incoming momentum no longer covers the row. (The simple2
 * miss that once motivated a tighter 0.85 was the executor sliding off the
 * stone, fixed by CHAIN_TAKEOFF_FRACTION + the landing-tick rollout gate.)
 */
export const CHAIN_MIN_COS = 0.70
/**
 * Turn loss of a chain re-jump at the EXECUTOR's cadence (jump pressed on
 * the landing tick, J_CHAIN's own measurement): the landing velocity has
 * had one ground tick to rotate toward the new heading, so the reach falls
 * with the turn — measured (turnChain1.ts, standing first hop): 0° 3.70,
 * 30° 3.60, 45° 3.47, 60° 3.30 flat; −1: 4.30, 4.19, 4.05, 3.85 — a
 * straight line in cos, 0.8 blocks per unit. (The 0°→60° table in
 * VelocityInSearch.md was taken one tick later, where the turn costs
 * less; that cadence is not the executor's.) Applied with
 * allowParkourMomentum: usable = J_CHAIN − CHAIN_TURN_LOSS × (1 − cos).
 */
export const CHAIN_TURN_LOSS = 0.8
/**
 * The re-jump's takeoff credit is HALF the standing creep credit of the
 * stone (min(TAKEOFF_STAND, half + margin) / 2): the first hop is aimed
 * that far past the stone's centre (Move.aimDx/aimDz), which keeps the
 * landing a hitbox inside the edge — aiming at the lip itself put the body
 * five centimetres from the edge at speed and it slid off (simple2).
 */
export const CHAIN_TAKEOFF_FRACTION = 0.5

/**
 * Head-hitter class: the same takeoffs under a solid lid 2 above the feet —
 * the jump bonks at +0.2 rise (prismarine-physics collision, simulated
 * exactly) and flies a flattened arc. +1 landings are impossible (−0.2
 * sentinel row), drops keep most of their reach: this is how players hop
 * gaps in 2-high tunnels and drop off ledges under an overhang.
 */
export const J_LOW_STANDING: readonly number[] = [
  -0.1, 0.9626976143129206, 1.8600178263100626, 2.292732225692906, 2.748396619821839, 2.9835742558313516, 3.466483304979486, 3.7134731393248104, 3.9637138885790555, 4.216912970400419
]

export const J_LOW_RUNNING: readonly number[] = [
  -0.1, 0.8703333522885409, 2.0076952770607037, 2.5757621249691116, 2.8596729923790343, 3.4272852710242216, 3.7109990552891845, 3.9946585989703007, 4.278268783720117, 4.56183405184245
]

/**
 * Takeoff credits. Standing: the executor creeps along the flight line
 * (sneaking) until the widest axis offset reaches TAKEOFF_STAND — center at
 * 0.6 leaves a 0.2-deep support patch under the hitbox (overhang limit is
 * 0.8). Measured on the arena route book: crediting the physical lip (0.78)
 * on full blocks re-plans routes over marginal standing jumps and the
 * executor then falls off them (simple2 +7 damage, parkour1 lost); the
 * patch is what keeps it robust to server corrections. Narrow supports are
 * different — see TAKEOFF_NARROW_MARGIN. Running: the executor's per-tick
 * rollout delays the jump up to the lip; 0.4 along the line is conservative
 * against the sim's jump-at-center measurement.
 */
export const TAKEOFF_STAND = 0.6
export const TAKEOFF_RUN = 0.4
/** Per-axis landing catch: half block + hitbox radius (overhang catch). */
export const LAND_HALF = 0.8

/**
 * NARROW-SUPPORT credits (topCatchClass > 0: fence posts, heads, pots —
 * shapes.ts). Same two formulas as the full-block constants, parameterized
 * by the support's centered top half-extent `c` (CATCH_HALF[class]):
 *   takeoff  = min(TAKEOFF_STAND, c + 0.28): the lip, two centimetres
 *              inside the overhang limit c + 0.3 — on a 1x1 post there is no
 *              other takeoff, and "jump exactly from the corner" is how the
 *              hard hops of a post course are made; a full block keeps its
 *              0.6 (the cap), see TAKEOFF_STAND.
 *   landing  = c + 0.3  (near-edge catch: half-extent + hitbox radius —
 *              0.5 + 0.3 = the 0.8 above)
 * Sneak's edge guard (prismarine-physics implements it) works on any
 * support, so the creep is safe on a post; what shrinks is simply how far
 * out the lip is. Running takeoffs are only generated from class-0 supports
 * — nothing narrower can host a run-up.
 */
export const TAKEOFF_NARROW_MARGIN = 0.28
export const LAND_NARROW_MARGIN = 0.3

/**
 * LIP take-off (allowParkourMomentum): a RUNNING body leaves from the
 * support's overhang limit, half + 0.3, whatever the tick phase. The engine
 * resolves the y axis (which sets onGround) before a tick's horizontal
 * move, so the flag lags a tick and the jump input on the first airborne
 * tick still fires — vanilla's late jump. The last tick with the hitbox
 * over the block is ≤ half + 0.3 past centre; the jump then fires from
 * there plus one sprint stride. Measured on the arena's parkouradv1 stair
 * (bench/arena/.run/scratch/trace.ts): grounded at 0.78, flagged at 1.06,
 * jumped there. The executor's delayed-jump rollout finds that tick. The
 * corridor is bounded over the whole window [limit, limit + LIP_STRIDE]
 * (parkourTable.ts mfLip). Standing creep jumps keep TAKEOFF_STAND.
 *
 * The take-off is credited at the MEDIAN of that window (limit + LIP_PHASE):
 * where in the stride the last grounded tick falls is set by the approach,
 * so half of all run-ins fly further than this and half shorter; a run-in
 * whose phase falls short is refused by the rollout and re-tried from the
 * executor's back-off, which samples the other phases (plugin.ts). Measured
 * on parkouradv1's fence→fence (3,−3,5): the brute force lands it from
 * 0.68 past the post's centre, the minimum phase (0.425) is 0.05 short.
 */
export const LIP_STRIDE = 0.28
export const LIP_PHASE = LIP_STRIDE / 2

/**
 * Slime-bounce apex per drop height d (blocks above the slime top after a
 * straight free fall of d blocks onto it, no controls) — index d, 2 … 8;
 * deeper drops clamp to index 8 (conservative: deeper = higher rebound).
 * Derived by test/helpers/jumpEnvelope.ts measureSlimeBounce() from
 * prismarine-physics (vel.y reflects on the contact tick, unless sneaking);
 * envelope.test.ts re-derives and asserts equality. The rebound apex is
 * control-independent — air movement never changes vel.y.
 */
export const BOUNCE_APEX: readonly number[] = [
  0, 0, 1.299059403294517, 2.1016917686844407, 2.5491276710482,
  3.5285290916089673, 4.052437529400663, 4.592855224215983, 5.161928468689879
]
export const BOUNCE_MAX_DROP = 8
/** Planning margin below the exact apex: ring-1 targets (adjacent to the
 * slime) get the full rebound minus this; ring-2 targets need extra descent
 * time to drift 2 cells, so they give up a full block of the apex. */
export const BOUNCE_MARGIN = 0.2
export const BOUNCE_MARGIN_FAR = 1.0

/**
 * Flight distance (center travel) needed for landing offset (a, b) from a
 * takeoff at per-axis position T on the takeoff block: the distance from T
 * to the landing catch square (a ± LAND_HALF) × (b ± LAND_HALF).
 */
export function flightNeeded (a: number, b: number, tx: number, tz: number): number {
  const dx = Math.max(0, Math.abs(a - tx) - LAND_HALF)
  const dz = Math.max(0, Math.abs(b - tz) - LAND_HALF)
  return Math.hypot(dx, dz)
}

/** Standing takeoff point: along the flight line, widest axis at TAKEOFF_STAND. */
export function takeoffStand (a: number, b: number): [number, number] {
  const dist = Math.hypot(a, b)
  const s = TAKEOFF_STAND * dist / Math.max(Math.abs(a), Math.abs(b))
  return [a / dist * s, b / dist * s]
}

/** Running takeoff point: TAKEOFF_RUN along the flight line. */
export function takeoffRun (a: number, b: number): [number, number] {
  const dist = Math.hypot(a, b)
  return [a / dist * TAKEOFF_RUN, b / dist * TAKEOFF_RUN]
}

/**
 * Envelope bucket for a landing dy blocks above (+) / below (−) the takeoff.
 * Drops deeper than -8 clamp to the -8 bucket (deeper = more airtime = more
 * reach, so the clamp is conservative; maxDropDown caps depth separately).
 */
export function reachBucket (dy: number): number {
  const b = 1 - dy
  return b >= ENVELOPE_BUCKETS ? ENVELOPE_BUCKETS - 1 : b
}

/**
 * Offset enumeration cap: the octile heuristic minus euclidean distance
 * peaks at ~0.082·major (minor/major = √2−1), so majors ≤ 6 keep the
 * deficit under the +0.5 cost pad — every enumerated move stays at or above
 * the heuristic. Feasibility (fnRun within the deepest running bucket)
 * prunes the rest at table-build time.
 */
export const MAX_OFFSET_MAJOR = 6

/**
 * Airborne flight curves [dx0, dy0, dx1, dy1, …] per tick — dx from the
 * takeoff-cell center along the flight line, dy (feet) from the takeoff walk
 * level. Generated by test/helpers/jumpEnvelope.ts measureFlightCurve();
 * envelope.test.ts re-derives and asserts equality. The arc is
 * target-independent (the executor holds forward+sprint+jump for every
 * jump), so one curve per takeoff class bounds the feet height at any
 * horizontal progress — parkourTable.ts derives per-corridor-cell clearance
 * floors from it, which is what lets drop-jumps fly over same-level corners
 * near takeoff instead of demanding full landing-depth clearance everywhere.
 */
export const FLIGHT_STANDING: readonly number[] = [
  0.32740005009235773, 0.41999998688697815,
  0.531640477442785, 0.7531999805212017,
  0.7429792663316739, 1.0013359791121474,
  0.9607775642205627, 1.1661092609382138,
  1.1844540152994516, 1.249187078744681,
  1.4134795857812406, 1.2522033402537236,
  1.6473728549196682, 1.1767592750642368,
  1.8856957298356374, 1.0244240882136797,
  2.1280495460091697, 0.7967356006686916,
  2.374071518727084, 0.4952008770059113,
  2.6234315139003863, 0.12129684053918921,
  2.875829109508091, -0.32352912385573096,
  3.1309909215111023, -0.8378585789730135,
  3.3886681704338426, -1.4203014563238852,
  3.6486344669535367, -2.0694954887628345,
  3.910683796786458, -2.7841056544612774,
  4.174628686934416, -3.562823632001737,
  4.440298536969059, -4.404367266370134,
  4.707538100500583, -5.307480045628211,
  4.97620610331427, -6.270930588052516,
  5.246173985874726, -7.293512139530574,
  5.51732475900474, -8.374042081009145,
  5.789551962553054, -9.511361445793497
]

export const FLIGHT_RUNNING: readonly number[] = [
  0.6856746083861516, 0.41999998688697815,
  0.9703333522885409, 0.7531999805212017,
  1.254852809239715, 1.0013359791121474,
  1.5392455150652835, 1.1661092609382138,
  1.8235228773665506, 1.249187078744681,
  2.107695277060704, 1.2522033402537236,
  2.3917721607823834, 1.1767592750642368,
  2.6757621249691117, 1.0244240882136797,
  2.9596729923790344, 0.7967356006686916,
  3.243511881722064, 0.4952008770059113,
  3.5272852710242217, 0.12129684053918921,
  3.8109990552891846, -0.32352912385573096,
  4.094658598970301, -0.8378585789730135,
  4.378268783720117, -1.4203014563238852,
  4.661834051842449, -2.0694954887628345,
  4.945358445833771, -2.7841056544612774,
  5.228845644365875, -3.562823632001737,
  5.512298995030089, -4.404367266370134,
  5.795721544134524, -5.307480045628211,
  6.079116063819559, -6.270930588052516,
  6.362485076732942, -7.293512139530574,
  6.64583087848412, -8.374042081009145,
  6.929155558077692, -9.511361445793497
]

/** Head-hitter flight curves (lid 2 above the feet; bonk at +0.2). */
export const FLIGHT_LOW_STANDING: readonly number[] = [
  0.32740005009235773, 0.20000000000000018,
  0.531640477442785, 0.12159999847412117,
  0.7429792663316739, 0,
  1.0626976143129205, 0,
  1.364663882403039, -0.07840000152587889,
  1.5550174647802435, -0.23363200604248047,
  1.7537192247434996, -0.46415937495544446,
  1.9600178263100627, -0.7684762024129888,
  2.173229553735635, -1.1451067006516438,
  2.3927322256929062, -1.5926045976350616,
  2.6179596571740227, -2.1095525467400345,
  2.848396619821839, -2.694561548248787,
  3.0835742558313517, -3.3462703824114044,
  3.3230659046000084, -4.063345053847008,
  3.566483304979486, -4.844478247056892,
  3.8134731393248105, -5.68838879282739,
  4.063713888579056, -6.593821145304674,
  4.316912970400419, -7.559544869528043,
  4.57280413485786, -8.584354139212541,
  4.831145094514131, -9.667067244575914
]

export const FLIGHT_LOW_RUNNING: readonly number[] = [
  0.6856746083861516, 0.20000000000000018,
  0.9703333522885409, 0.12159999847412117,
  1.254852809239715, -0.0336320060424804,
  1.5392455150652835, -0.2641593749554444,
  1.8235228773665506, -0.5684762024129886,
  2.107695277060704, -0.9451067006516438,
  2.3917721607823834, -1.3926045976350614,
  2.6757621249691117, -1.9095525467400347,
  2.9596729923790344, -2.494561548248787,
  3.243511881722064, -3.146270382411404,
  3.5272852710242217, -3.8633450538470075,
  3.8109990552891846, -4.644478247056892,
  4.094658598970301, -5.48838879282739,
  4.378268783720117, -6.393821145304674,
  4.661834051842449, -7.359544869528042,
  4.945358445833771, -8.38435413921254,
  5.228845644365875, -9.467067244575913
]

/**
 * Feet height (blocks above takeoff walk level) at horizontal progress `d`
 * along the flight line, linearly interpolated between ticks. Before the
 * first airborne tick the bound is the ground (0); past the last tick it
 * clamps to the last sample (deeper than any allowed drop).
 */
export function feetAt (curve: readonly number[], d: number): number {
  if (d <= curve[0]) return 0
  for (let i = 2; i < curve.length; i += 2) {
    if (d <= curve[i]) {
      const f = (d - curve[i - 2]) / (curve[i] - curve[i - 2])
      return curve[i - 1] + (curve[i + 1] - curve[i - 1]) * f
    }
  }
  return curve[curve.length - 1]
}
