// Parkour reach envelope, DERIVED from prismarine-physics — the exact engine
// (and held controls: forward+sprint+jump) the executor uses to gate every
// jump at run time. Generated by test/helpers/jumpEnvelope.ts;
// test/envelope.test.ts re-derives and asserts equality, so these values can
// never silently drift from the real physics.
//
// J[bucket] = usable flight distance (pure center travel minus a 0.2 safety
// margin) for a landing at dy = +1 (bucket 0), 0 (bucket 1), -1 … -8
// (buckets 2…9). Take-off and landing geometry is credited PER-AXIS by
// flightNeeded(): the 0.6-wide hitbox takes off from the block's corner and
// catches the landing block's near corner, so a diagonal (3,3) hop needs
// only ~2.26 blocks of flight, not the 4.24 center-to-center distance —
// exactly how players cross 1x1 pillar courses from a standstill.

export const ENVELOPE_BUCKETS = 10

/** Standing start (a 1x1 pillar: no room to build sprint momentum). Pure
 * jam from the cell center; the executor creeps to the takeoff corner
 * (TAKEOFF_STAND per axis) before jumping — that credit is applied by
 * flightNeeded, not baked into these rows. */
export const J_STANDING: readonly number[] = [
  1.6856957298356374, 2.423431513900386, 2.930990921511102,
  3.1886681704338424, 3.7106837967864577, 3.974628686934416,
  4.240298536969059, 4.507538100500583, 4.77620610331427, 5.046173985874725
]

/** Running start (≥1 walkable same-level cell behind the takeoff). Measured
 * with the jump firing at the cell center; the executor's rollout delays the
 * jump toward the lip, credited as TAKEOFF_RUN along the flight line. */
export const J_RUNNING: readonly number[] = [
  2.4757621249691115, 3.3272852710242216, 3.8946585989703006,
  4.1782687837201165, 4.745358445833771, 5.028845644365875,
  5.312298995030089, 5.595721544134523, 5.879116063819559, 6.162485076732942
]

/**
 * Head-hitter class: the same takeoffs under a solid lid 2 above the feet —
 * the jump bonks at +0.2 rise (prismarine-physics collision, simulated
 * exactly) and flies a flattened arc. +1 landings are impossible (−0.2
 * sentinel row), drops keep most of their reach: this is how players hop
 * gaps in 2-high tunnels and drop off ledges under an overhang.
 */
export const J_LOW_STANDING: readonly number[] = [
  -0.2, 0.8626976143129206, 1.7600178263100628,
  2.192732225692906, 2.6483966198218387, 2.8835742558313515,
  3.366483304979486, 3.6134731393248103, 3.8637138885790554, 4.116912970400419
]

export const J_LOW_RUNNING: readonly number[] = [
  -0.2, 0.7703333522885409, 1.9076952770607039,
  2.4757621249691115, 2.759672992379034, 3.3272852710242216,
  3.6109990552891844, 3.8946585989703006, 4.1782687837201165, 4.461834051842449
]

/**
 * Takeoff credits. Standing: the executor creeps along the flight line until
 * the widest axis offset reaches TAKEOFF_STAND — center at 0.6 leaves a
 * 0.2-deep support patch under the hitbox (overhang limit is 0.8). Running:
 * the executor's per-tick rollout delays the jump up to the lip; 0.4 along
 * the line is conservative against the sim's jump-at-center measurement.
 */
export const TAKEOFF_STAND = 0.6
export const TAKEOFF_RUN = 0.4
/** Per-axis landing catch: half block + hitbox radius (overhang catch). */
export const LAND_HALF = 0.8

/**
 * Flight distance (center travel) needed for landing offset (a, b) from a
 * takeoff at per-axis position T on the takeoff block: the distance from T
 * to the landing catch square (a ± LAND_HALF) × (b ± LAND_HALF).
 */
export function flightNeeded (a: number, b: number, tx: number, tz: number): number {
  const dx = Math.max(0, Math.abs(a - tx) - LAND_HALF)
  const dz = Math.max(0, Math.abs(b - tz) - LAND_HALF)
  return Math.hypot(dx, dz)
}

/** Standing takeoff point: along the flight line, widest axis at TAKEOFF_STAND. */
export function takeoffStand (a: number, b: number): [number, number] {
  const dist = Math.hypot(a, b)
  const s = TAKEOFF_STAND * dist / Math.max(Math.abs(a), Math.abs(b))
  return [a / dist * s, b / dist * s]
}

/** Running takeoff point: TAKEOFF_RUN along the flight line. */
export function takeoffRun (a: number, b: number): [number, number] {
  const dist = Math.hypot(a, b)
  return [a / dist * TAKEOFF_RUN, b / dist * TAKEOFF_RUN]
}

/**
 * Envelope bucket for a landing dy blocks above (+) / below (−) the takeoff.
 * Drops deeper than -8 clamp to the -8 bucket (deeper = more airtime = more
 * reach, so the clamp is conservative; maxDropDown caps depth separately).
 */
export function reachBucket (dy: number): number {
  const b = 1 - dy
  return b >= ENVELOPE_BUCKETS ? ENVELOPE_BUCKETS - 1 : b
}

/**
 * Offset enumeration cap: the octile heuristic minus euclidean distance
 * peaks at ~0.082·major (minor/major = √2−1), so majors ≤ 6 keep the
 * deficit under the +0.5 cost pad — every enumerated move stays at or above
 * the heuristic. Feasibility (fnRun within the deepest running bucket)
 * prunes the rest at table-build time.
 */
export const MAX_OFFSET_MAJOR = 6

/**
 * Airborne flight curves [dx0, dy0, dx1, dy1, …] per tick — dx from the
 * takeoff-cell center along the flight line, dy (feet) from the takeoff walk
 * level. Generated by test/helpers/jumpEnvelope.ts measureFlightCurve();
 * envelope.test.ts re-derives and asserts equality. The arc is
 * target-independent (the executor holds forward+sprint+jump for every
 * jump), so one curve per takeoff class bounds the feet height at any
 * horizontal progress — parkourTable.ts derives per-corridor-cell clearance
 * floors from it, which is what lets drop-jumps fly over same-level corners
 * near takeoff instead of demanding full landing-depth clearance everywhere.
 */
export const FLIGHT_STANDING: readonly number[] = [
  0.32740005009235773, 0.41999998688697815,
  0.531640477442785, 0.7531999805212017,
  0.7429792663316739, 1.0013359791121474,
  0.9607775642205627, 1.1661092609382138,
  1.1844540152994516, 1.249187078744681,
  1.4134795857812406, 1.2522033402537236,
  1.6473728549196682, 1.1767592750642368,
  1.8856957298356374, 1.0244240882136797,
  2.1280495460091697, 0.7967356006686916,
  2.374071518727084, 0.4952008770059113,
  2.6234315139003863, 0.12129684053918921,
  2.875829109508091, -0.32352912385573096,
  3.1309909215111023, -0.8378585789730135,
  3.3886681704338426, -1.4203014563238852,
  3.6486344669535367, -2.0694954887628345,
  3.910683796786458, -2.7841056544612774,
  4.174628686934416, -3.562823632001737,
  4.440298536969059, -4.404367266370134,
  4.707538100500583, -5.307480045628211,
  4.97620610331427, -6.270930588052516,
  5.246173985874726, -7.293512139530574,
  5.51732475900474, -8.374042081009145,
  5.789551962553054, -9.511361445793497
]

export const FLIGHT_RUNNING: readonly number[] = [
  0.6856746083861516, 0.41999998688697815,
  0.9703333522885409, 0.7531999805212017,
  1.254852809239715, 1.0013359791121474,
  1.5392455150652835, 1.1661092609382138,
  1.8235228773665506, 1.249187078744681,
  2.107695277060704, 1.2522033402537236,
  2.3917721607823834, 1.1767592750642368,
  2.6757621249691117, 1.0244240882136797,
  2.9596729923790344, 0.7967356006686916,
  3.243511881722064, 0.4952008770059113,
  3.5272852710242217, 0.12129684053918921,
  3.8109990552891846, -0.32352912385573096,
  4.094658598970301, -0.8378585789730135,
  4.378268783720117, -1.4203014563238852,
  4.661834051842449, -2.0694954887628345,
  4.945358445833771, -2.7841056544612774,
  5.228845644365875, -3.562823632001737,
  5.512298995030089, -4.404367266370134,
  5.795721544134524, -5.307480045628211,
  6.079116063819559, -6.270930588052516,
  6.362485076732942, -7.293512139530574,
  6.64583087848412, -8.374042081009145,
  6.929155558077692, -9.511361445793497
]

/** Head-hitter flight curves (lid 2 above the feet; bonk at +0.2). */
export const FLIGHT_LOW_STANDING: readonly number[] = [
  0.32740005009235773, 0.20000000000000018,
  0.531640477442785, 0.12159999847412117,
  0.7429792663316739, 0,
  1.0626976143129205, 0,
  1.364663882403039, -0.07840000152587889,
  1.5550174647802435, -0.23363200604248047,
  1.7537192247434996, -0.46415937495544446,
  1.9600178263100627, -0.7684762024129888,
  2.173229553735635, -1.1451067006516438,
  2.3927322256929062, -1.5926045976350616,
  2.6179596571740227, -2.1095525467400345,
  2.848396619821839, -2.694561548248787,
  3.0835742558313517, -3.3462703824114044,
  3.3230659046000084, -4.063345053847008,
  3.566483304979486, -4.844478247056892,
  3.8134731393248105, -5.68838879282739,
  4.063713888579056, -6.593821145304674,
  4.316912970400419, -7.559544869528043,
  4.57280413485786, -8.584354139212541,
  4.831145094514131, -9.667067244575914
]

export const FLIGHT_LOW_RUNNING: readonly number[] = [
  0.6856746083861516, 0.20000000000000018,
  0.9703333522885409, 0.12159999847412117,
  1.254852809239715, -0.0336320060424804,
  1.5392455150652835, -0.2641593749554444,
  1.8235228773665506, -0.5684762024129886,
  2.107695277060704, -0.9451067006516438,
  2.3917721607823834, -1.3926045976350614,
  2.6757621249691117, -1.9095525467400347,
  2.9596729923790344, -2.494561548248787,
  3.243511881722064, -3.146270382411404,
  3.5272852710242217, -3.8633450538470075,
  3.8109990552891846, -4.644478247056892,
  4.094658598970301, -5.48838879282739,
  4.378268783720117, -6.393821145304674,
  4.661834051842449, -7.359544869528042,
  4.945358445833771, -8.38435413921254,
  5.228845644365875, -9.467067244575913
]

/**
 * Feet height (blocks above takeoff walk level) at horizontal progress `d`
 * along the flight line, linearly interpolated between ticks. Before the
 * first airborne tick the bound is the ground (0); past the last tick it
 * clamps to the last sample (deeper than any allowed drop).
 */
export function feetAt (curve: readonly number[], d: number): number {
  if (d <= curve[0]) return 0
  for (let i = 2; i < curve.length; i += 2) {
    if (d <= curve[i]) {
      const f = (d - curve[i - 2]) / (curve[i] - curve[i - 2])
      return curve[i - 1] + (curve[i + 1] - curve[i - 1]) * f
    }
  }
  return curve[curve.length - 1]
}
